name: boilerplate
description: Boilerplate Code.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Media
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  image_picker: ^0.8.7+5
  file_picker: ^5.3.0
  path_provider: ^2.0.15
  mime: ^1.0.4

  # UI
  responsive_framework: ^0.2.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_sliders: ^21.2.4

  # Web
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.0

  # State Management
  provider: ^6.0.5

  # Local DB
  shared_preferences: ^2.1.1

  # Network
  http: ^0.13.6
  dio_http_cache_lts: ^0.4.1
  web_socket_channel: ^2.4.0

  # Encryption
  encrypt: ^5.0.1

  # Loading/Animation
  shimmer: ^2.0.0
  flutter_spinkit: ^5.2.0
  lottie: ^2.3.2

  # Location/Map
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.6
  flutter_polyline_points: ^1.0.0

  # Other
  collection: ^1.17.0
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.1
  intl: ^0.18.0
  permission_handler: ^10.2.0

  # Payment
  flutter_sslcommerz: ^2.2.2-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/animations/

  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/icons/app_icon.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
          style: normal

        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
          style: normal

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal

        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
          style: normal

        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
